forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt',
  :git => "https://github.com/puppetlabs/puppetlabs-apt.git",
  :ref => '3.0.0'

mod 'puppetlabs/java',
  :git => 'https://github.com/puppetlabs/puppetlabs-java.git',
  :ref => '1.6.0'
